modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/personality/issues"
license = "https://github.com/team-abnormals/personality/blob/main/LICENSE"

[[mods]]
    modId = "personality"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "minecraft:oak_stairs"
    configBackground = "minecraft:textures/block/oak_planks.png"
    authors = "Team Abnormals"
    credits = "Jackson and bageldotjpg"
    displayURL = "https://www.teamabnormals.com/mods/personality"
    displayName = "Personality"
    description = '''
    Adds more cosmetic features and animations to players, as well as new player actions like sitting and crawling.
    '''

[[dependencies.personality]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,1.19.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.personality]]
    modId = "forge"
    mandatory = true
    versionRange = "[41.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.personality]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.0.4,)"
    ordering = "AFTER"
    side = "BOTH"